name: Compile Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet restore ${{ github.event.repository.name }}.sln
      - uses: justalemon/VersionPatcher@v0.8
        with:
          version: 1.10.0.${{ github.run_number }}
          use-tag: true
          csproj-files: "**/*.csproj"
      - run: dotnet build ${{ github.event.repository.name }}.sln -c ${{ matrix.configuration }}
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
  docs:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx.json
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "docs/_site"
      - uses: actions/deploy-pages@v4.0.5
  github-package-registry:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/bin/Release/*
      - run: dotnet nuget push "**/*.nupkg" -s 'https://nuget.pkg.github.com/${{ github.event.repository.owner.name }}/index.json' -k ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/bin/Release/*
      - run: dotnet nuget push "**/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{ secrets.NUGET }}
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ github.event.repository.name }}.zip
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
